### PR TITLE
Watch jade files not scoped to app/pages (?)

### PR DESCRIPTION
**Pull request by niklasfasching**
Hey, it's late and I'm new to github so take a look while keeping this in mind :)

I think the watch for jadePages could be set to only look at .jade files in the "app/page" directory.

### CODE REVIEW

**Comment by jayharris** [comment]
Nice catch!

However, I think you meant it without a the space between `pageRoot` and `pages`. With the space, the glob does not resolve.

Also, as a handy side-effect of the old way, it would also run `jade:pagesDev` whenever a template changed. It is not uncommon for a Jade page to use a template as it's base layout. I think it would be beneficial to include `<%= files.jade.templates %>` in the watched file array for `jade:pagesDev`. This way, if the base template changed, the pages would also be regenerated.

An example of base layouts:

_./app/pages/index.jade_

``` jade
extends ../templates/layout.jade

block content
  p My Content goes here
```

_./app/templates/layout.jade_

``` jade
doctype html
html
  head
    title #{pkg.title}
    link(rel="stylesheet" type="text/css" href="#{css}" media="all")
  body
    block content
    script(type="text/javascript" src="#{js}")
```

**Comment by niklasfasching** [comment]
Hey

Thanks for the thorough explanation. Your solution sounds great - I didn't think about jade blocks and just tried to lower my cpu load as too many files were being watched I think.

**Comment by jayharris** [comment]
That makes complete sense, and I think updating the Files list to Pages and Templates is worthwhile.
If you like, revise the pull request; it was your catch, after all.

**Comment by jayharris** [comment]
:+1:

**Pull request merged**
